// Seed the bundled "Recipe Box" sample project on first launch.
//
// A brand-new install opens onto an empty window — nothing to look at, no way to
// see what Build / Plan / Team / Trace actually do. This copies a small, real
// sample project out of the app bundle into `~/AuraProjects/recipe-box` so every
// surface has genuine state the moment the app opens: a task board mid-flight, a
// trace with reasons, teammates, notes, and two manager-chat conversations (one
// finished, one still running).
//
// The `.aura/` state is NOT hand-faked. It was produced by driving the real
// `aura` engine over a five-commit build of Recipe Box: each intent is a real
// Ed25519-signed block under `.aura/attest/` (with `.aura/team/keys.jsonl` so
// `aura attest verify` passes offline on any install), and commit four is a REAL
// recorded scope-divergence — the agent declared it would touch `app.js` only,
// also edited `recipes.js`, and the commit-time reconciler caught it. That
// caught block is what the Trace tab shows off. Regenerated by
// `aura-shell/scripts/build-recipe-box-sample.sh <aura-bin> <out-repo>`, whose
// `.aura/{attest,blocks,intent_log.jsonl,team/keys.jsonl}` + code files are then
// copied into `resources/sample-project/` (with `.aura/` shipped as `dot-aura/`).
//
// Two shipping quirks it handles:
//   1. The project's `.aura/` dir ships as `dot-aura/` — a leading-dot dir
//      doesn't bundle cleanly — so it's renamed back to `.aura/` at seed time.
//   2. Every file carries `{{PROJECT_ROOT}}` + relative-time placeholders
//      (`{{T_MINUS_3H}}`, `{{ISO_MINUS_2D}}`, …). We fill them from the real
//      destination path and the current clock so the history reads as recent.
//
// Idempotent: if the destination already exists and is non-empty we return it
// untouched, so re-launches never re-seed or clobber the user's edits.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use chrono::Utc;
use serde::Serialize;
use tauri::path::BaseDirectory;
use tauri::{AppHandle, Manager};

/// What the seed command hands back to the frontend. `root` goes straight to
/// `loadProjectAt`; `ambient_session_id` is the live chat to focus so the Build
/// surface opens on a real conversation.
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SeededSample {
    pub root: String,
    pub name: String,
    pub ambient_session_id: String,
}

const SAMPLE_NAME: &str = "recipe-box";
/// The "running" chat in resources/sample-sessions — focused after seeding.
const AMBIENT_SESSION_ID: &str = "aura-sample-search";

fn home_dir() -> Result<PathBuf, String> {
    dirs::home_dir().ok_or_else(|| "could not resolve home directory".to_string())
}

/// Build the placeholder → value map. All time offsets derive from a single
/// `now` so the seeded files stay internally consistent. `{{T_MINUS_*}}` are
/// unix seconds (bare numbers in JSON); `{{ISO_MINUS_*}}` are RFC3339 strings.
fn build_substitutions(project_root: &str) -> HashMap<String, String> {
    let now_dt = Utc::now();
    let now = now_dt.timestamp();
    const H: i64 = 3600;
    const D: i64 = 86400;
    let secs_ago = |s: i64| (now - s).to_string();
    let ms_ago = |s: i64| ((now - s) * 1000).to_string();
    let iso_ago = |s: i64| (now_dt - chrono::Duration::seconds(s)).to_rfc3339();

    let mut m = HashMap::new();
    m.insert("{{PROJECT_ROOT}}".to_string(), project_root.to_string());
    m.insert("{{T_MINUS_2D}}".to_string(), secs_ago(2 * D));
    m.insert("{{T_MINUS_46H}}".to_string(), secs_ago(46 * H));
    m.insert("{{T_MINUS_1D}}".to_string(), secs_ago(D));
    m.insert("{{T_MINUS_3H}}".to_string(), secs_ago(3 * H));
    m.insert("{{T_MINUS_2H}}".to_string(), secs_ago(2 * H));
    m.insert("{{T_MINUS_1H}}".to_string(), secs_ago(H));
    m.insert("{{T_MINUS_45H}}".to_string(), secs_ago(45 * H));
    m.insert("{{T_MINUS_20M}}".to_string(), secs_ago(20 * 60));
    m.insert("{{ISO_MINUS_2D}}".to_string(), iso_ago(2 * D));
    m.insert("{{ISO_MINUS_1D}}".to_string(), iso_ago(D));
    m.insert("{{ISO_MINUS_20M}}".to_string(), iso_ago(20 * 60));
    // Unix millis (bare numbers) for `.aura/goals.jsonl`, whose timestamps are
    // milliseconds, not seconds — keeps the seeded proof runs reading "2 days
    // ago" instead of drifting to a frozen date.
    m.insert("{{MS_MINUS_2D}}".to_string(), ms_ago(2 * D));
    m.insert("{{MS_MINUS_1D}}".to_string(), ms_ago(D));
    m.insert("{{MS_MINUS_20M}}".to_string(), ms_ago(20 * 60));
    m
}

fn apply_subs(text: &str, subs: &HashMap<String, String>) -> String {
    let mut out = text.to_string();
    for (k, v) in subs {
        if out.contains(k) {
            out = out.replace(k, v);
        }
    }
    out
}

/// Recursively copy `src` → `dst`. A dir literally named `dot-aura` is written
/// out as `.aura` (see module note). Text files get placeholder substitution;
/// anything that isn't valid UTF-8 is copied byte-for-byte.
fn copy_tree(src: &Path, dst: &Path, subs: &HashMap<String, String>) -> Result<(), String> {
    for entry in fs::read_dir(src).map_err(|e| format!("read {}: {e}", src.display()))? {
        let entry = entry.map_err(|e| e.to_string())?;
        let raw = entry.file_name();
        let name = raw.to_string_lossy();
        let out_name = if name == "dot-aura" { ".aura" } else { name.as_ref() };
        let child_src = entry.path();
        let child_dst = dst.join(out_name);
        if child_src.is_dir() {
            fs::create_dir_all(&child_dst)
                .map_err(|e| format!("create {}: {e}", child_dst.display()))?;
            copy_tree(&child_src, &child_dst, subs)?;
        } else {
            let bytes =
                fs::read(&child_src).map_err(|e| format!("read {}: {e}", child_src.display()))?;
            match String::from_utf8(bytes) {
                Ok(text) => fs::write(&child_dst, apply_subs(&text, subs)),
                Err(e) => fs::write(&child_dst, e.into_bytes()),
            }
            .map_err(|e| format!("write {}: {e}", child_dst.display()))?;
        }
    }
    Ok(())
}

/// Drop the bundled chat-session templates into `~/.aura/manager-sessions`,
/// substituting placeholders. Never clobbers an existing file (so a real
/// session that somehow shares the name is safe).
fn seed_sessions(
    src_sessions: &Path,
    sessions_dir: &Path,
    subs: &HashMap<String, String>,
) -> Result<(), String> {
    if !src_sessions.is_dir() {
        return Ok(());
    }
    fs::create_dir_all(sessions_dir)
        .map_err(|e| format!("create {}: {e}", sessions_dir.display()))?;
    for entry in
        fs::read_dir(src_sessions).map_err(|e| format!("read {}: {e}", src_sessions.display()))?
    {
        let entry = entry.map_err(|e| e.to_string())?;
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("json") {
            continue;
        }
        let out = sessions_dir.join(entry.file_name());
        if out.exists() {
            continue;
        }
        let text = fs::read_to_string(&path).map_err(|e| format!("read {}: {e}", path.display()))?;
        fs::write(&out, apply_subs(&text, subs))
            .map_err(|e| format!("write {}: {e}", out.display()))?;
    }
    Ok(())
}

/// `git init` + one commit so the sample is a real repo (Trace/history work and
/// Aura treats it as a project). Uses the user's git identity when they have one,
/// falling back to a neutral local identity so the commit never fails on a fresh
/// machine. Git failures are non-fatal — the seeded files are what matter.
fn git_init_commit(dest: &Path) {
    let git = |args: &[&str]| {
        Command::new("git")
            .args(args)
            .current_dir(dest)
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    };
    if !git(&["init"]) {
        return;
    }
    // -b main isn't universal across git versions; rename after init instead.
    let _ = git(&["symbolic-ref", "HEAD", "refs/heads/main"]);
    // Only set a local identity if the user has none globally, so their real
    // name/email drive Team + Trace when present.
    let has_identity = Command::new("git")
        .args(["config", "user.email"])
        .current_dir(dest)
        .output()
        .map(|o| !o.stdout.is_empty())
        .unwrap_or(false);
    if !has_identity {
        let _ = git(&["config", "user.email", "you@example.com"]);
        let _ = git(&["config", "user.name", "You"]);
    }
    let _ = git(&["add", "-A"]);
    let _ = git(&[
        "-c",
        "commit.gpgsign=false",
        "commit",
        "-m",
        "Recipe Box — sample project",
    ]);
}

#[tauri::command]
pub async fn seed_sample_project(app: AppHandle) -> Result<SeededSample, String> {
    let home = home_dir()?;
    let dest = home.join("AuraProjects").join(SAMPLE_NAME);
    let dest_str = dest.to_string_lossy().to_string();

    let result = SeededSample {
        root: dest_str.clone(),
        name: SAMPLE_NAME.to_string(),
        ambient_session_id: AMBIENT_SESSION_ID.to_string(),
    };

    let subs = build_substitutions(&dest_str);

    // Top up the bundled chat sessions FIRST — before the project-tree
    // idempotency guard below. `seed_sessions` never clobbers an existing file,
    // so it's safe to run on every call; doing it up here means installs whose
    // recipe-box dir predates session-seeding (or had `~/.aura/manager-sessions`
    // cleared) still get the sample conversations, instead of the guard skipping
    // straight past them and leaving the Get Started workspace looking empty.
    // Best-effort: a missing sessions resource just means no sample chats, never
    // a failed seed of the project itself.
    if let Ok(src_sessions) = app
        .path()
        .resolve("resources/sample-sessions", BaseDirectory::Resource)
    {
        let sessions_dir = home.join(".aura").join("manager-sessions");
        let _ = seed_sessions(&src_sessions, &sessions_dir, &subs);
    }

    // Idempotent: a populated destination means we already seeded the project
    // tree — leave it (and its git history) be. The sample chats were handled
    // just above, independent of this guard.
    if dest.exists()
        && fs::read_dir(&dest)
            .map(|mut d| d.next().is_some())
            .unwrap_or(false)
    {
        return Ok(result);
    }

    // Resolve the bundled project tree (source dir in `tauri dev`, inside the
    // app bundle when packaged).
    let src_project = app
        .path()
        .resolve("resources/sample-project", BaseDirectory::Resource)
        .map_err(|e| format!("locate sample-project resource: {e}"))?;
    if !src_project.is_dir() {
        return Err(format!(
            "bundled sample project missing at {}",
            src_project.display()
        ));
    }

    // 1) Materialize the project tree (dot-aura → .aura, placeholders filled).
    fs::create_dir_all(&dest).map_err(|e| format!("create {}: {e}", dest.display()))?;
    copy_tree(&src_project, &dest, &subs)?;

    // 2) Make it a real git repo.
    git_init_commit(&dest);

    // 3) Prime a semantic checkpoint so `aura prove` works on the sample the
    //    moment it opens. The prover reads the latest checkpoint from git notes
    //    (`refs/notes/aura`), which only exists after a capture. `--force`
    //    bypasses the strict intent gate (a fresh checkout has no prior
    //    checkpoint, so every node reads as "new" and un-forced capture would
    //    halt asking for an intent). The bundled intent blocks already carry
    //    their actual_impacts, so this capture only checkpoints — it won't
    //    re-run the scope-divergence catch. Best-effort: a missing/old `aura`
    //    on PATH just means prove waits for the first real capture the user
    //    triggers by editing. Resolve the binary through the shared resolver so
    //    it still lands when the GUI PATH probe misses (honors $AURA_BIN and the
    //    `~/.cargo/bin/aura` fallback).
    let _ = Command::new(crate::agent_event_listener::resolve_aura_bin())
        .args(["capture-context", "--force"])
        .current_dir(&dest)
        .output();

    Ok(result)
}
