//! Install OSC 133 prompt markers for zsh / bash so every user-typed command
//! creates a block, not just composer-submitted ones.
//!
//! Zsh: we write a synthetic `$ZDOTDIR/.zshrc` into a process-unique temp
//! directory and export `ZDOTDIR=<that>` via the environment the PTY shell
//! inherits (added via the `env` field on `alacritty_terminal::tty::Options`).
//! The .zshrc sources the user's normal `~/.zshrc` first (so their PATH,
//! aliases, prompt, etc. stay intact) then adds `precmd`/`preexec` hooks
//! that emit OSC 133 A/B/C/D sequences around every command.
//!
//! Bash: we'd use `--rcfile`, but that requires passing a flag to the shell
//! args. For v1 we only ship the zsh integration because that's macOS's
//! default shell. Bash users fall back to composer-only auto-close.

use std::fs;
use std::path::PathBuf;

use crate::error::{Result, TermError};

const ZSHRC_CONTENTS: &str = r#"# Aura OSC 133 shell integration — generated by aura-proto.
# Source the user's normal zshrc so their prompt + aliases + PATH stay.
if [[ -f "$HOME/.zshrc" ]]; then
  source "$HOME/.zshrc"
fi

# Emit OSC 133;A just before the prompt paints.
__aura_osc_prompt_start() {
  printf '\033]133;A\007'
}
# Emit OSC 133;B at the start of the user-input region (right after the prompt).
# zsh's PROMPT is printed then the user types — we piggyback on precmd to emit
# both A and B on the same line so tools that only read A still work.
__aura_osc_command_input_start() {
  printf '\033]133;B\007'
}
# Emit OSC 133;C just before a command starts executing.
__aura_osc_command_exec_start() {
  printf '\033]133;C\007'
}
# Emit OSC 133;D with exit status after a command finishes.
__aura_osc_command_end() {
  local ec=$?
  printf '\033]133;D;%d\007' "$ec"
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd __aura_osc_command_end
add-zsh-hook precmd __aura_osc_prompt_start
add-zsh-hook precmd __aura_osc_command_input_start
add-zsh-hook preexec __aura_osc_command_exec_start
"#;

/// Prepare an OSC 133 shell-integration directory for zsh. Returns the
/// absolute path to use as `ZDOTDIR`. Idempotent per-install: the directory
/// lives under `$TMPDIR/aura-proto-shell/<pid>` so each run writes a fresh
/// one and old ones age out with the tempdir.
pub fn prepare_zsh_zdotdir() -> Result<PathBuf> {
    let mut dir = std::env::temp_dir();
    dir.push("aura-proto-shell");
    dir.push(std::process::id().to_string());
    fs::create_dir_all(&dir).map_err(TermError::Io)?;
    let zshrc = dir.join(".zshrc");
    fs::write(&zshrc, ZSHRC_CONTENTS).map_err(TermError::Io)?;
    Ok(dir)
}

/// True iff the given shell path looks like zsh.
pub fn is_zsh(shell: &str) -> bool {
    std::path::Path::new(shell)
        .file_name()
        .and_then(|s| s.to_str())
        .map(|s| s == "zsh")
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn is_zsh_matches_full_path() {
        assert!(is_zsh("/bin/zsh"));
        assert!(is_zsh("/opt/homebrew/bin/zsh"));
        assert!(!is_zsh("/bin/bash"));
        assert!(!is_zsh("/bin/sh"));
    }

    #[test]
    fn prepare_zsh_zdotdir_writes_zshrc() {
        let dir = prepare_zsh_zdotdir().expect("prep");
        let zshrc = dir.join(".zshrc");
        assert!(zshrc.exists(), "zshrc at {zshrc:?}");
        let body = std::fs::read_to_string(&zshrc).unwrap();
        assert!(body.contains("OSC 133"));
        assert!(body.contains("add-zsh-hook preexec __aura_osc_command_exec_start"));
    }
}
