//! Generates `BlockKind` enum from `kinds.toml` at build time.
//!
//! There is intentionally no `Custom` variant. Every legal kind lives in the
//! registry; adding one is a code-review checkpoint.

use serde::Deserialize;
use std::{env, fs, path::PathBuf};

#[derive(Deserialize)]
struct Registry {
    schema_version: SchemaVersion,
    kinds: Vec<Kind>,
}

#[derive(Deserialize)]
struct SchemaVersion {
    major: u16,
    minor: u16,
    patch: u16,
}

#[derive(Deserialize)]
struct Kind {
    name: String,
    wire: String,
    doc: String,
}

fn main() {
    println!("cargo:rerun-if-changed=kinds.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let toml_src = fs::read_to_string("kinds.toml").expect("read kinds.toml");
    let reg: Registry = toml::from_str(&toml_src).expect("parse kinds.toml");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from kinds.toml — DO NOT EDIT.\n\n");

    // SchemaVersion constant mirroring the registry declaration.
    out.push_str(&format!(
        "pub const KINDS_REGISTRY_VERSION: crate::SchemaVersion = crate::SchemaVersion {{ major: {}, minor: {}, patch: {} }};\n\n",
        reg.schema_version.major, reg.schema_version.minor, reg.schema_version.patch
    ));

    // Enum declaration.
    out.push_str("/// The set of legal block kinds. Generated from `kinds.toml`.\n");
    out.push_str("///\n");
    out.push_str("/// There is no `Custom` variant. Adding a kind requires editing the registry.\n");
    out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]\n");
    out.push_str("#[serde(tag = \"kind\", rename_all = \"snake_case\")]\n");
    out.push_str("pub enum BlockKind {\n");
    for k in &reg.kinds {
        out.push_str(&format!("    /// {}\n", k.doc));
        out.push_str(&format!("    #[serde(rename = \"{}\")]\n", k.wire));
        out.push_str(&format!("    {},\n", k.name));
    }
    out.push_str("}\n\n");

    // Helpers: wire string, name, all().
    out.push_str("impl BlockKind {\n");
    out.push_str("    /// Stable on-wire discriminator.\n");
    out.push_str("    pub fn wire(&self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for k in &reg.kinds {
        out.push_str(&format!(
            "            Self::{} => \"{}\",\n",
            k.name, k.wire
        ));
    }
    out.push_str("        }\n    }\n\n");

    out.push_str("    /// All registered kinds, in registry order.\n");
    out.push_str("    pub fn all() -> &'static [BlockKind] {\n");
    out.push_str("        &[\n");
    for k in &reg.kinds {
        out.push_str(&format!("            BlockKind::{},\n", k.name));
    }
    out.push_str("        ]\n    }\n\n");

    // Parser: wire string -> Option<BlockKind>.
    out.push_str("    /// Parse a wire-format discriminator string into a variant.\n");
    out.push_str("    /// Returns `None` for unknown kinds — callers decide policy on\n");
    out.push_str("    /// unknown wire tags (typically refuse to load the document).\n");
    out.push_str("    pub fn from_serde_name(s: &str) -> Option<Self> {\n");
    out.push_str("        match s {\n");
    for k in &reg.kinds {
        out.push_str(&format!(
            "            \"{}\" => Some(Self::{}),\n",
            k.wire, k.name
        ));
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n    }\n");
    out.push_str("}\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("block_kind.rs"), out).expect("write block_kind.rs");
}
