//! GitHub Actions export — emit a `.github/workflows/aura.yml` that runs the
//! SAME `.aura/pipelines/*.toml` in the cloud on every PR. Aura provides the
//! semantic step verbs; GitHub provides the compute.
//!
//! The exported workflow is deliberately thin: it checks the repo out with full
//! history (`fetch-depth: 0`, so AST diffs against the base resolve), installs
//! the `aura` CLI, then runs `aura ci run --trigger pr` against
//! `origin/<base_ref>`. Blocking steps fail the job because `aura ci run`
//! returns a non-zero exit code when the run is blocked. There is no second
//! source of truth — the pipeline TOML drives both the local hooks and this
//! workflow.

use crate::model::Pipeline;

/// Render the GitHub Actions workflow YAML for `pipelines`. The pipelines list
/// is used only to name the job and document which checks will run as comments;
/// the actual gate selection happens at runtime from the same TOML, so the
/// workflow never drifts from the local hooks.
pub fn github_workflow(pipelines: &[Pipeline]) -> String {
    let mut checks_doc = String::new();
    for p in pipelines {
        checks_doc.push_str(&format!("#   pipeline `{}`:\n", p.name));
        for step in &p.steps {
            let kind = match &step.kind {
                crate::model::StepKind::Gate(id) => format!("gate {}", id),
                crate::model::StepKind::Run(cmd) => format!("run `{}`", cmd),
            };
            let posture = if step.blocking { "blocking" } else { "advisory" };
            checks_doc.push_str(&format!("#     - {} ({}, {})\n", step.name, kind, posture));
        }
    }

    format!(
        r#"# Aura Semantic CI — generated by `aura ci export`.
#
# This workflow runs the SAME .aura/pipelines/*.toml your local git hooks run,
# so the cloud and your machine check identical gates. Edit the pipeline TOML
# (not this file) to change what runs; re-run `aura ci export` to refresh.
#
# Checks that will run on every PR:
{checks_doc}name: Aura Semantic CI

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  semantic-ci:
    name: Semantic CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for AST diffs)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Aura CLI
        run: |
          curl -fsSL https://auravcs.com/install.sh | sh
          echo "$HOME/.aura/bin" >> "$GITHUB_PATH"
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      - name: Run Semantic CI
        run: |
          BASE="origin/${{{{ github.base_ref || github.event.repository.default_branch }}}}"
          aura ci run --trigger pr --base "$BASE" --json | tee aura-ci-result.json
          # `aura ci run` exits non-zero when a blocking step fails.

      - name: Upload Semantic CI result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: aura-semantic-ci
          path: aura-ci-result.json
"#,
        checks_doc = checks_doc,
    )
}

/// The default output path for the workflow.
pub const DEFAULT_WORKFLOW_PATH: &str = ".github/workflows/aura-checks.yml";

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::default_pipeline;

    #[test]
    fn workflow_has_required_pieces() {
        let yaml = github_workflow(&[default_pipeline()]);
        assert!(yaml.contains("fetch-depth: 0"), "needs full history");
        assert!(yaml.contains("Install Aura CLI"));
        assert!(yaml.contains("aura ci run --trigger pr"));
        assert!(yaml.contains("--base"));
        // The pipeline's gates are documented as comments.
        assert!(yaml.contains("gate no-secrets"));
        assert!(yaml.contains("gate build"));
    }
}
