//! Loro CRDT substrate — **cloud-side only**.
//!
//! This crate is a dependency of `aura-cloud` (see `loro_sync.rs`, `live.rs`),
//! where Loro backs the server-side dual-write of zones + the intent log into a
//! conflict-free document. It is **not** the substrate used by the CLI live-sync
//! hot path: `aura-cli` syncs whole files and function bodies over `yrs`
//! (`aura-cli/src/crdt.rs`, `crdt_daemon.rs`) and does not depend on this crate.
//! Don't reach for `aura-crdt-core` when working on CLI/desktop live sync — that
//! path is `yrs`.

use chrono::{DateTime, Utc};
use loro::{LoroDoc, LoroMap, UndoManager, ToJson};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct TeamMessage {
    pub id: Uuid,
    pub sender_id: Uuid,
    pub content: String,
    pub timestamp: DateTime<Utc>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ZoneClaim {
    pub id: Uuid,
    pub zone_path: String,
    pub claim_type: String,
    pub status: String,
    pub critical: bool,
    pub claimant_id: Uuid,
    pub timestamp: DateTime<Utc>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct IntentLogEntry {
    pub id: Uuid,
    pub user_id: Uuid,
    pub intent_type: String,
    pub summary: String,
    pub file_path: String,
    pub lamport_clock: u64, // Semantic ordering layer
    pub timestamp: DateTime<Utc>,
}

pub struct CrdtDoc {
    doc: LoroDoc,
    undo_manager: UndoManager,
}

impl Default for CrdtDoc {
    fn default() -> Self {
        Self::new()
    }
}

impl CrdtDoc {
    pub fn new() -> Self {
        let doc = LoroDoc::new();
        let undo_manager = UndoManager::new(&doc);
        Self { doc, undo_manager }
    }

    pub fn doc(&self) -> &LoroDoc {
        &self.doc
    }

    pub fn undo_manager(&mut self) -> &mut UndoManager {
        &mut self.undo_manager
    }

    pub fn record_checkpoint(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        self.undo_manager.record_new_checkpoint(&self.doc)?;
        Ok(())
    }

    pub fn aura_rewind_op(&mut self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        // Record checkpoint before undoing
        self.undo_manager.record_new_checkpoint(&self.doc)?;
        
        if self.undo_manager.can_undo() {
            let vv_before = self.doc.oplog_vv();
            self.undo_manager.undo(&self.doc)?;
            // Export the new ops generated by the undo as an inverse patch
            let update = self.doc.export_from(&vv_before);
            Ok(update)
        } else {
            Err("No operations to undo".into())
        }
    }

    pub fn get_messages(&self) -> Vec<TeamMessage> {
        let list = self.doc.get_list("messages");
        let mut messages = Vec::new();
        
        let val = list.get_deep_value();
        if let Ok(json) = serde_json::to_value(&val.to_json_value()) {
            if let Ok(arr) = serde_json::from_value::<Vec<TeamMessage>>(json) {
                messages = arr;
            }
        }
        messages
    }

    pub fn add_message(&self, msg: &TeamMessage) -> Result<(), Box<dyn std::error::Error>> {
        let list = self.doc.get_list("messages");
        let map = list.insert_container(list.len(), LoroMap::new())?;
        map.insert("id", msg.id.to_string().as_str())?;
        map.insert("sender_id", msg.sender_id.to_string().as_str())?;
        map.insert("content", msg.content.as_str())?;
        map.insert("timestamp", msg.timestamp.to_rfc3339().as_str())?;
        Ok(())
    }

    pub fn get_zones(&self) -> Vec<ZoneClaim> {
        let list = self.doc.get_list("zones");
        let mut zones = Vec::new();
        
        let val = list.get_deep_value();
        if let Ok(json) = serde_json::to_value(&val.to_json_value()) {
            if let Ok(arr) = serde_json::from_value::<Vec<ZoneClaim>>(json) {
                zones = arr;
            }
        }
        zones
    }

    pub fn add_zone(&self, zone: &ZoneClaim) -> Result<(), Box<dyn std::error::Error>> {
        let list = self.doc.get_list("zones");
        let map = list.insert_container(list.len(), LoroMap::new())?;
        map.insert("id", zone.id.to_string().as_str())?;
        map.insert("zone_path", zone.zone_path.as_str())?;
        map.insert("claim_type", zone.claim_type.as_str())?;
        map.insert("status", zone.status.as_str())?;
        map.insert("critical", zone.critical)?;
        map.insert("claimant_id", zone.claimant_id.to_string().as_str())?;
        map.insert("timestamp", zone.timestamp.to_rfc3339().as_str())?;
        Ok(())
    }

    pub fn get_intent_log(&self) -> Vec<IntentLogEntry> {
        let list = self.doc.get_list("intent_log");
        let mut intents = Vec::new();
        
        let val = list.get_deep_value();
        if let Ok(json) = serde_json::to_value(&val.to_json_value()) {
            if let Ok(arr) = serde_json::from_value::<Vec<IntentLogEntry>>(json) {
                intents = arr;
            }
        }
        // Semantic Ordering Layer: guarantee causal sorting by Lamport clock, fallback to timestamp
        intents.sort_by(|a, b| {
            let clock_cmp = a.lamport_clock.cmp(&b.lamport_clock);
            if clock_cmp == std::cmp::Ordering::Equal {
                a.timestamp.cmp(&b.timestamp)
            } else {
                clock_cmp
            }
        });
        intents
    }

    pub fn add_intent(&self, intent: &IntentLogEntry) -> Result<(), Box<dyn std::error::Error>> {
        let list = self.doc.get_list("intent_log");
        let map = list.insert_container(list.len(), LoroMap::new())?;
        map.insert("id", intent.id.to_string().as_str())?;
        map.insert("user_id", intent.user_id.to_string().as_str())?;
        map.insert("intent_type", intent.intent_type.as_str())?;
        map.insert("summary", intent.summary.as_str())?;
        map.insert("file_path", intent.file_path.as_str())?;
        map.insert("lamport_clock", intent.lamport_clock as i64)?;
        map.insert("timestamp", intent.timestamp.to_rfc3339().as_str())?;
        Ok(())
    }

    pub async fn load<P: LoroPersistence>(persistence: &P, doc_id: Uuid) -> Result<Self, String> {
        let doc = LoroDoc::new();
        let undo_manager = UndoManager::new(&doc);
        let mut has_data = false;

        if let Ok(Some(snapshot)) = persistence.load_latest_snapshot(doc_id).await {
            doc.import(&snapshot).map_err(|e| e.to_string())?;
            has_data = true;
        }

        if let Ok(ops) = persistence.load_operations_since(doc_id, &[]).await {
            for op in ops {
                doc.import(&op).map_err(|e| e.to_string())?;
                has_data = true;
            }
        }

        // Setup schema versioning if new
        if !has_data {
            let map = doc.get_map("metadata");
            let _ = map.insert("schema_version", 1);
        }

        Ok(Self { doc, undo_manager })
    }

    /// Performs CRDT compaction by generating a new base snapshot and archiving/deleting old ops
    pub async fn compact<P: LoroPersistence>(&self, persistence: &P, doc_id: Uuid, repo_id: Uuid) -> Result<(), String> {
        let snapshot = self.doc.export_snapshot();
        persistence.save_snapshot(doc_id, repo_id, &snapshot, &[]).await?;
        persistence.prune_operations(doc_id).await?;
        Ok(())
    }

    pub fn apply_and_validate(&self, updates: &[u8], acting_user: Uuid) -> Result<(), String> {
        // Clone doc to validate changes before applying to main doc
        let test_doc = LoroDoc::new();
        test_doc.import(&self.doc.export_snapshot()).map_err(|e| e.to_string())?;
        
        // Apply the untrusted updates to the clone
        test_doc.import(updates).map_err(|e| e.to_string())?;
        
        // Task 3.3: Business Rule Validation
        let list = test_doc.get_list("messages");
        let val = list.get_deep_value();
        
        if let Ok(json) = serde_json::to_value(&val.to_json_value()) {
            if let Ok(arr) = serde_json::from_value::<Vec<TeamMessage>>(json) {
                for msg in arr {
                    // Rule 1: Content cannot be empty
                    if msg.content.trim().is_empty() {
                        return Err("Message content cannot be empty".to_string());
                    }
                    // Rule 2: Content cannot be too long
                    if msg.content.len() > 10000 {
                        return Err("Message content exceeds 10000 characters".to_string());
                    }
                }
            } else {
                return Err("Failed to deserialize messages".to_string());
            }
        }
        
        // Validation passed, apply to main doc
        self.doc.import(updates).map_err(|e| e.to_string())?;
        Ok(())
    }

    pub fn export_updates(&self) -> Vec<u8> {
        self.doc.export_from(&loro::VersionVector::new())
    }
}

pub trait LoroPersistence {
    async fn save_snapshot(&self, doc_id: Uuid, repo_id: Uuid, snapshot_bytes: &[u8], version_vector: &[u8]) -> Result<(), String>;
    async fn append_operations(&self, doc_id: Uuid, operations_bytes: &[u8], version_vector_after: &[u8]) -> Result<(), String>;
    async fn load_latest_snapshot(&self, doc_id: Uuid) -> Result<Option<Vec<u8>>, String>;
    async fn load_operations_since(&self, doc_id: Uuid, version_vector: &[u8]) -> Result<Vec<Vec<u8>>, String>;
    async fn prune_operations(&self, doc_id: Uuid) -> Result<(), String>;
}
