//! Whether an intent row was written by a person or composed by a machine.
//!
//! Three surfaces ask this question about the same rows, so the rules live in
//! one crate rather than three copies of themselves:
//!
//! * the CLI, naming a session it synthesised from `.aura/intent_log.jsonl`
//! * the cloud, naming the same session after those rows are pushed
//! * the console, rendering the log (`aura-console/src/lib/intentGrammar.ts`,
//!   which stays a deliberate mirror because it runs in a browser)
//!
//! Almost every row is a hook capture. The agent hooks spell it two ways:
//!
//! ```text
//! log_intent "$AGENT $TOOL_NAME on $REL_PATH"   -> "Claude Edit on src/x.ts"
//! log_intent "$AGENT $TOOL_NAME: $BASH_CMD"     -> "Claude Bash: cd /repo && ls"
//! ```
//!
//! and the desktop's tool-use listener spells the same thing verb-first with
//! no agent name: "ran Bash on rm -rf build". A row matching none of those is
//! the rare and valuable one: a sentence somebody actually wrote.
//!
//! Why anyone cares: a synthesised session takes its objective from its
//! earliest row, and the earliest row of a session is almost always a hook
//! capture — so sessions were called "Claude Bash: cd ..." and, where the
//! agent had nothing else to say yet, just "Claude". An objective is what the
//! session set out to do. Only a sentence can be that.
//!
//! A leaf crate: every rule here is a pure function of the row's own text, it
//! has no dependencies, and it reads no files.
const SHELL_TOOLS: &[&str] = &["Bash", "Shell", "run_shell_command", "run_terminal_cmd"];

/// `<Agent> <ShellTool>: <command>` — the hook's shell capture.
fn is_command_capture(text: &str) -> bool {
    let Some((head, _)) = text.split_once(':') else {
        return false;
    };
    let mut parts = head.split_whitespace();
    let Some(_agent) = parts.next() else {
        return false;
    };
    let Some(tool) = parts.next() else {
        return false;
    };
    // Exactly two words before the colon, or it is prose that happens to
    // contain one — "Rewrote the loader: it blocked paint" must not match.
    parts.next().is_none() && SHELL_TOOLS.contains(&tool)
}

/// `running|ran <Tool> [on <target>]` — the desktop listener's spelling.
fn is_listener_capture(text: &str) -> bool {
    let mut parts = text.split_whitespace();
    let Some(verb) = parts.next() else {
        return false;
    };
    if !matches!(verb, "running" | "ran") {
        return false;
    }
    // A tool name is one word. "ran the migration by hand" is a sentence.
    let Some(_tool) = parts.next() else {
        return false;
    };
    match parts.next() {
        None => true,
        Some("on") => true,
        Some(_) => false,
    }
}

/// `<Agent> <Tool> on <path>` — recognised only when the row also carries the
/// path in its own column and the sentence ends with exactly that string.
///
/// That pairing is what makes this safe to run over every row: a real sentence
/// about a file ("Moved the retry helper on to the shared client") does not
/// end in the exact contents of its own `file_path`.
fn is_file_capture(text: &str, file_path: Option<&str>) -> bool {
    let Some(path) = file_path.map(str::trim).filter(|p| !p.is_empty()) else {
        return false;
    };
    let text = text.trim();
    if text == path {
        return true;
    }
    let tail = format!(" on {path}");
    let Some(prefix) = text.strip_suffix(&tail) else {
        return false;
    };
    // "Claude Edit" — an agent and a tool, nothing more. Any longer and it is
    // a sentence that happens to end where the path does.
    !prefix.trim().is_empty() && prefix.split_whitespace().count() <= 2
}

/// Openings that belong to the agent harness rather than to a person.
///
/// A long-running session gets its context compacted, and the tool writes the
/// continuation itself: *"This session is being continued from a previous
/// conversation that ran out of context…"*. Whatever captures the first
/// message of a resumed session captures that too, so it arrives looking
/// exactly like a sentence somebody typed.
///
/// This matters more here than it looks. A written objective **latches** — the
/// whole point of preferring it is that no later hook capture can take it back
/// — so a preamble admitted once becomes that session's permanent description.
const HARNESS_PREAMBLE: &[&str] = &[
    "this session is being continued from a previous conversation",
    "caveat: the messages below were generated by the user while running",
    "please continue the conversation from where we left it off",
    "your task is to create a detailed summary of the conversation",
    "<command-name>",
    "<system-reminder>",
    "<local-command-stdout>",
];

/// Whether a line is the harness talking to itself.
///
/// Matched on the opening rather than anywhere in the text: somebody writing
/// "the summary says we ran out of context, so…" is stating an objective, and
/// only a line that *begins* this way is the tool's own.
fn is_harness_preamble(text: &str) -> bool {
    let flat = text.trim().to_lowercase();
    HARNESS_PREAMBLE.iter().any(|opening| flat.starts_with(opening))
}

/// True when a person composed this row, rather than a hook.
pub fn is_written_by_a_person(text: &str, file_path: Option<&str>) -> bool {
    let text = text.trim();
    if text.is_empty() {
        return false;
    }
    !is_command_capture(text)
        && !is_listener_capture(text)
        && !is_file_capture(text, file_path)
        && !is_harness_preamble(text)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_hooks_shell_capture_is_not_an_objective() {
        assert!(!is_written_by_a_person("Claude Bash: cd \"/repo\" && ls", None));
        assert!(!is_written_by_a_person("Gemini run_shell_command: git status", None));
    }

    #[test]
    fn a_compaction_preamble_is_the_harness_talking_to_itself() {
        // This one is load-bearing: a written objective latches, so admitting
        // a preamble once makes it the session's description for good.
        assert!(!is_written_by_a_person(
            "This session is being continued from a previous conversation that ran out of context. The summary below covers the earlier portion.",
            None
        ));
        assert!(!is_written_by_a_person(
            "Caveat: The messages below were generated by the user while running local commands.",
            None
        ));
        assert!(!is_written_by_a_person("<command-name>/compact</command-name>", None));
    }

    #[test]
    fn a_person_mentioning_context_still_wrote_it() {
        // The rule reads the opening, not the vocabulary — otherwise it eats a
        // real objective for containing the same phrase.
        assert!(is_written_by_a_person(
            "The summary says we ran out of context, so rebuild the Changes pane to match the desktop app.",
            None
        ));
    }

    #[test]
    fn the_desktop_listeners_spelling_is_not_either() {
        assert!(!is_written_by_a_person("ran Bash on rm -rf build", None));
        assert!(!is_written_by_a_person("running Edit", None));
    }

    #[test]
    fn a_file_touch_is_not_an_objective() {
        assert!(!is_written_by_a_person(
            "Claude Edit on aura-cli/src/sync.rs",
            Some("aura-cli/src/sync.rs"),
        ));
    }

    #[test]
    fn a_sentence_that_ends_where_the_path_does_is_still_a_sentence() {
        // The pairing rule earns its keep here: without the word count this
        // would be swallowed as a capture.
        assert!(is_written_by_a_person(
            "Moved the retry helper on to the shared client on src/client.ts",
            Some("src/client.ts"),
        ));
    }

    #[test]
    fn prose_containing_a_colon_is_not_a_shell_capture() {
        assert!(is_written_by_a_person(
            "Rewrote the loader: a cold start was blocking paint",
            None,
        ));
    }

    #[test]
    fn prose_starting_with_ran_is_not_a_listener_capture() {
        assert!(is_written_by_a_person("ran the migration by hand on staging", None));
    }

    #[test]
    fn a_sentence_somebody_wrote_is_an_objective() {
        assert!(is_written_by_a_person(
            "Switch the retry to exponential backoff so we stop tripping the rate limit",
            Some("aura-cli/src/sync.rs"),
        ));
    }

    #[test]
    fn an_empty_row_names_nothing() {
        assert!(!is_written_by_a_person("   ", None));
    }
}
