//! Safe OSC-133 shell-integration injection for plain terminals.
//!
//! We never edit the user's real rc files. Instead:
//!   * **zsh** — point `ZDOTDIR` at a per-session throwaway dir holding
//!     `.zshenv` / `.zprofile` / `.zshrc` / `.zlogin`, each of which
//!     re-sources the user's real counterpart (flipping `ZDOTDIR` back
//!     to the user's dir while it sources, then restoring ours). The
//!     `.zshrc` additionally appends the OSC-133 hook block. This is the
//!     exact dance VS Code's zsh integration uses so the user's full
//!     startup (env, profile, aliases, theme) loads unchanged.
//!   * **bash** — spawn with `--rcfile <temp>` whose body sources the
//!     user's `~/.bashrc` then appends the hooks. (`--rcfile` replaces
//!     the default interactive rc, so we re-source theirs.)
//!
//! Any other shell (fish / nu / sh / …) → `None`, spawn proceeds clean.
//! Gated upstream by the `terminal.shell_integration` pref AND the
//! profile's opt-in, so this is only ever called when the user wants it.

use std::path::PathBuf;

/// What a prepared integration contributes to the child spawn.
pub struct ShellIntegration {
    /// Extra env to set on the child (`ZDOTDIR` for zsh).
    pub env: Vec<(String, String)>,
    /// Extra args to prepend (`--rcfile <path>` for bash).
    pub args: Vec<String>,
}

const ZSH_HOOKS: &str =
    include_str!("../../resources/shell-integration/aura-shell-integration.zsh");
const BASH_HOOKS: &str =
    include_str!("../../resources/shell-integration/aura-shell-integration.bash");

/// Prepare OSC-133 injection for `shell_path`, or `None` if it's not a
/// shell we know how to hook. `term_id` namespaces the per-session temp
/// dir so concurrent terminals never share a ZDOTDIR/rcfile.
pub fn prepare(shell_path: &str, term_id: &str) -> Option<ShellIntegration> {
    let base = std::path::Path::new(shell_path)
        .file_name()?
        .to_string_lossy()
        .to_string();
    match base.as_str() {
        "zsh" => prepare_zsh(term_id),
        "bash" => prepare_bash(term_id),
        _ => None,
    }
}

fn integ_dir(term_id: &str) -> Option<PathBuf> {
    let safe: String = term_id
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-' || *c == '_')
        .collect();
    let mut p = PathBuf::from(std::env::var_os("HOME")?);
    p.push(".aura");
    p.push("run");
    p.push("shell-integration");
    p.push(safe);
    Some(p)
}

fn prepare_zsh(term_id: &str) -> Option<ShellIntegration> {
    let dir = integ_dir(term_id)?;
    std::fs::create_dir_all(&dir).ok()?;
    let our = dir.to_string_lossy().into_owned();

    // The user's effective ZDOTDIR (their real config home). zsh defaults
    // it to $HOME when unset.
    let user_zdotdir = std::env::var("ZDOTDIR")
        .ok()
        .filter(|s| !s.is_empty())
        .or_else(|| std::env::var("HOME").ok())?;

    // Each scaffold file re-sources the user's same-named rc with ZDOTDIR
    // temporarily pointed back at their dir, then restores ours so the
    // NEXT file in zsh's load order (zshenv → zprofile → zshrc → zlogin)
    // still comes from our dir. AURA_ZDOTDIR/USER_ZDOTDIR are also passed
    // as child env (below) so these expand even on the very first file.
    let scaffold = |name: &str, extra: &str| -> String {
        format!(
            "# Auto-generated by Aura terminal. Sources your real {name},\n\
             # then (for .zshrc) layers OSC-133 marks. Never edits your files.\n\
             if [[ -f \"$USER_ZDOTDIR/{name}\" ]]; then\n\
             \x20 ZDOTDIR=\"$USER_ZDOTDIR\"\n\
             \x20 source \"$USER_ZDOTDIR/{name}\"\n\
             fi\n\
             ZDOTDIR=\"$AURA_ZDOTDIR\"\n\
             {extra}"
        )
    };

    std::fs::write(dir.join(".zshenv"), scaffold(".zshenv", "")).ok()?;
    std::fs::write(dir.join(".zprofile"), scaffold(".zprofile", "")).ok()?;
    std::fs::write(dir.join(".zlogin"), scaffold(".zlogin", "")).ok()?;
    std::fs::write(
        dir.join(".zshrc"),
        scaffold(".zshrc", &format!("\n# --- Aura OSC-133 hooks ---\n{ZSH_HOOKS}")),
    )
    .ok()?;

    Some(ShellIntegration {
        env: vec![
            ("ZDOTDIR".into(), our.clone()),
            ("AURA_ZDOTDIR".into(), our),
            ("USER_ZDOTDIR".into(), user_zdotdir),
        ],
        args: Vec::new(),
    })
}

fn prepare_bash(term_id: &str) -> Option<ShellIntegration> {
    let dir = integ_dir(term_id)?;
    std::fs::create_dir_all(&dir).ok()?;
    let rc_path = dir.join("aura-bashrc");
    let body = format!(
        "# Auto-generated by Aura terminal. Sources your ~/.bashrc, then\n\
         # layers OSC-133 marks. Never edits your files.\n\
         [ -f \"$HOME/.bashrc\" ] && source \"$HOME/.bashrc\"\n\
         {BASH_HOOKS}"
    );
    std::fs::write(&rc_path, body).ok()?;
    Some(ShellIntegration {
        env: Vec::new(),
        // `-i` forces interactive so PROMPT_COMMAND / PS1 / the DEBUG
        // trap actually run; `--rcfile` points bash at our wrapper.
        args: vec![
            "--rcfile".into(),
            rc_path.to_string_lossy().into_owned(),
            "-i".into(),
        ],
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unknown_shell_opts_out() {
        assert!(prepare("/usr/bin/fish", "t1").is_none());
        assert!(prepare("/bin/sh", "t2").is_none());
    }
}
